// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef main_h
#define main_h




#include <FL/Fl.H>
#include "util.h"
#include "source.h"
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *file_browser;
#include <FL/Fl_Check_Browser.H>
extern Fl_Check_Browser *choose_files;
#include <FL/Fl_Group.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>
extern Fl_Double_Window *window_main;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *main_menu;
extern void open_hex(Fl_Menu_*, void*);
extern void open_partial(Fl_Menu_*, void*);
extern void save_hex(Fl_Menu_*, void*);
extern void save_as_hex(Fl_Menu_*, void*);
extern void save_partial(Fl_Menu_*, void*);
extern void file_export(Fl_Menu_*, void*);
extern void quit_hex(Fl_Menu_*, void*);
extern void clear_hex(Fl_Menu_*, void*);
extern void view_hex(Fl_Menu_*, void*);
extern void view_octal(Fl_Menu_*, void*);
extern void parse_asd(Fl_Menu_*, void*);
extern void show_help(Fl_Menu_*, void*);
#include <FL/Fl_Text_Editor.H>
extern Fl_Text_Editor *hex_edit;
#include <FL/Fl_Scrollbar.H>
extern Fl_Scrollbar *hex_scroll;
extern Fl_Group *hex_group;
#include <FL/Fl_Box.H>
extern Fl_Box *main_mode;
extern Fl_Box *main_output;
extern Fl_Box *main_status;
#include <FL/Fl_Progress.H>
extern Fl_Progress *progress_bar;
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Output.H>
extern Fl_Output *hex_out;
extern Fl_Output *oct_out;
extern Fl_Output *bin_out;
extern Fl_Output *ascii_out;
extern Fl_Output *dec_out;
extern Fl_Output *etb_out;
extern Fl_Output *stb_out;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *sign_change;
#include <FL/Fl_Input.H>
extern void synchronize_offset_to_dec(Fl_Input*, void*);
extern Fl_Input *_offset_hex;
extern void synchronize_offset_to_hex(Fl_Input*, void*);
extern Fl_Input *_offset_dec;
extern void goto_offset(Fl_Button*, void*);
extern Fl_Button *gotooffset;
extern void refresh_offset(Fl_Group*, void*);
extern Fl_Group *query_field;
#include <FL/Fl_Text_Display.H>
extern void refresh_input(Fl_Text_Display*, void*);
extern Fl_Text_Display *view_header;
extern Fl_Input *offset_hex;
extern Fl_Input *offset_dec;
extern void restrict_word_length_dec(Fl_Input*, void*);
extern Fl_Input *bytes_number;
#include <FL/Fl_Input_Choice.H>
extern void bind_query_type(Fl_Input_Choice*, void*);
extern Fl_Input_Choice *field_type;
extern void get_value(Fl_Button*, void*);
extern Fl_Button *getvalue;
extern void save_value(Fl_Button*, void*);
extern Fl_Button *savevalue;
extern Fl_Menu_Item menu_main_menu[];
void make_window();
#endif
