#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC =
CFLAGS = -std=c++0x -Wall `fltk-config --cxxflags`
RESINC = 
LIBDIR =
#LIB = -l/usr/lib64/libfltk.a -lXcursor -lXfixes -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lX11
LIB = -lfltk -lXcursor -lXfixes -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lX11
#LDFLAGS = `fltk-config --ldstaticflags` `fltk-config --prefix`
LDFLAGS = `fltk-config --ldflags`

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -std=c++11 -std=c++0x -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/the

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -std=c++11 -s
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/the

OBJ_DEBUG = $(OBJDIR_DEBUG)/util.o $(OBJDIR_DEBUG)/source.o $(OBJDIR_DEBUG)/main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/util.o $(OBJDIR_RELEASE)/source.o $(OBJDIR_RELEASE)/main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/util.o: util.cxx
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c util.cxx -o $(OBJDIR_DEBUG)/util.o

$(OBJDIR_DEBUG)/source.o: source.cxx
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c source.cxx -o $(OBJDIR_DEBUG)/source.o

$(OBJDIR_DEBUG)/main.o: main.cxx
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cxx -o $(OBJDIR_DEBUG)/main.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/util.o: util.cxx
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c util.cxx -o $(OBJDIR_RELEASE)/util.o

$(OBJDIR_RELEASE)/source.o: source.cxx
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c source.cxx -o $(OBJDIR_RELEASE)/source.o

$(OBJDIR_RELEASE)/main.o: main.cxx
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cxx -o $(OBJDIR_RELEASE)/main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

